# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('person_type', models.CharField(choices=[('P', 'Professor'), ('E', 'Egresso'), ('A', 'Academico FASA'), ('O', 'Outro')], default='A', max_length=1, verbose_name='Tipo inscrito')),
                ('checked', models.BooleanField(default=False, verbose_name='E-mail v\xe1lido')),
            ],
            options={
                'verbose_name': 'Inscri\xe7\xe3o',
                'verbose_name_plural': 'Inscri\xe7\xf5es',
            },
        ),
    ]
