# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='T\xedtulo do curso')),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.TimeField(verbose_name='Hor\xe1rio')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Mini-curso',
                'verbose_name_plural': 'Mini-cursos',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('person_type', models.CharField(choices=[('Academico FASA', 'Academico FASA'), ('Outro', 'Outro'), ('Egresso', 'Egresso'), ('Professor', 'Professor')], default='A', max_length=15, verbose_name='Tipo inscrito')),
                ('registration', models.CharField(blank=True, max_length=6, null=True, verbose_name='Matr\xedcula')),
                ('event', models.BooleanField(default=False, verbose_name='Partcipar do evento')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('lecture', models.ManyToManyField(blank=True, null=True, to='subscription.Lecture', verbose_name='Mini-cursos')),
            ],
            options={
                'verbose_name': 'Inscri\xe7\xe3o',
                'verbose_name_plural': 'Inscri\xe7\xf5es',
            },
        ),
    ]
