# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='vacancies',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='N\xfamero de vagas'),
            preserve_default=False,
        ),
    ]
