# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_lecture_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=150, verbose_name='T\xedtulo do curso'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lecture',
            field=models.ManyToManyField(to='subscription.Lecture', verbose_name='Mini-cursos'),
        ),
    ]
