# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20160906_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='person_type',
            field=models.CharField(choices=[('3', 'Profissional'), ('2', 'Acad\xeamico outra institui\xe7\xe3o'), ('1', 'Acad\xeamico FASA')], default='1', max_length=15, verbose_name='Tipo inscrito'),
        ),
    ]
