# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0004_auto_20160928_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('in_out', models.PositiveSmallIntegerField(choices=[('E', 'Entrou'), ('S', 'Saiu')])),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription')),
            ],
            options={
                'verbose_name': 'Registro da portaria',
                'verbose_name_plural': 'Registros da portaria',
            },
        ),
    ]
